'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { keyOf } from './useMapDraft';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * What is selected, and nothing else.
 *
 * Held HERE rather than inside the canvas, because four surfaces need it and
 * only one of them is the canvas: the toolbar counts it and clears it, the
 * inspector decides which of three panels to show from it, the keyboard handler
 * deletes and duplicates it, and the canvas draws it.
 *
 * TWO SETS, NOT ONE, and it is worth saying why rather than tagging every id
 * with its kind. A table's identity is `keyOf` — an `id` for a saved row, a
 * `localKey` for one not saved yet — and a zone's is a string generated by
 * `newZoneId`. Both are opaque strings from different generators, and a single
 * set would work right up until they collided, at which point deleting a zone
 * would delete a table. Two sets make that impossible instead of unlikely.
 *
 * SELECTION IS NOT PART OF THE DRAFT, so it is not part of undo. Ctrl+Z steps
 * back a change to the room, never a change to what is highlighted — undoing
 * your way back through a series of clicks is the behaviour every editor that
 * tried it removed again.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const EMPTY = Object.freeze({ tables: new Set(), zones: new Set() });

export function useSelection() {
  const [selection, setSelection] = useState(EMPTY);

  /**
   * The live selection, readable from a pointer handler that was bound once.
   *
   * The drag and marquee handlers attach to `window` for the life of a gesture
   * and must not be re-bound on every selection change — rebinding mid-drag
   * drops the gesture. They read this instead of a captured value.
   *
   * SYNCED IN AN EFFECT, not during render. Assigning it in the render body is
   * the shorter version and React's compiler rejects it outright — a render
   * must be a pure function of its inputs, and a ref written there is a
   * side-effect that the compiler's re-ordering and re-running can duplicate or
   * skip. The effect runs after the commit and before any user event that
   * could read it, so there is no window in which this is stale.
   */
  const ref = useRef(selection);
  useEffect(() => { ref.current = selection; }, [selection]);

  const count = selection.tables.size + selection.zones.size;

  const clear = useCallback(() => setSelection((s) => (s.tables.size === 0 && s.zones.size === 0 ? s : EMPTY)), []);

  /** Replaces the selection with exactly one thing — a plain click. */
  const selectOnly = useCallback((kind, id) => {
    setSelection(kind === 'zone'
      ? { tables: new Set(), zones: new Set([id]) }
      : { tables: new Set([id]), zones: new Set() });
  }, []);

  /**
   * Adds or removes one thing — Ctrl/Cmd/Shift-click.
   *
   * Toggling rather than only adding is what makes a marquee correctable: you
   * sweep up eleven tables, then Ctrl-click the one you did not want back out,
   * instead of starting the sweep again.
   */
  const toggle = useCallback((kind, id) => {
    setSelection((s) => {
      const next = { tables: new Set(s.tables), zones: new Set(s.zones) };
      const set = kind === 'zone' ? next.zones : next.tables;
      if (set.has(id)) set.delete(id); else set.add(id);
      return next;
    });
  }, []);

  /** Wholesale replacement — what a finished marquee and "Select all" write. */
  const replace = useCallback((tables, zones) => {
    setSelection({ tables: new Set(tables || []), zones: new Set(zones || []) });
  }, []);

  /**
   * Adds a whole group to what is already selected — a Shift-marquee, and the
   * "Select all round tables" menu when it is used twice to build a union.
   */
  const extend = useCallback((tables, zones) => {
    setSelection((s) => ({
      tables: new Set([...s.tables, ...(tables || [])]),
      zones: new Set([...s.zones, ...(zones || [])]),
    }));
  }, []);

  /** True when a click on this thing should keep, not replace, the selection —
   *  it is already part of a group, and clicking to DRAG that group must not
   *  first collapse it to the one element under the cursor. */
  const has = useCallback((kind, id) => (kind === 'zone' ? selection.zones.has(id) : selection.tables.has(id)), [selection]);

  return useMemo(() => ({
    selection, ref, count, has, clear, selectOnly, toggle, replace, extend,
  }), [selection, count, has, clear, selectOnly, toggle, replace, extend]);
}

/**
 * The one thing selected, when exactly one thing is — which is what the
 * inspector needs to decide between the table panel, the zone panel and the
 * group panel.
 *
 * Returns `{ kind, table }` or `{ kind, zone }` or null. Null both when nothing
 * is selected and when several are, because the inspector treats those
 * differently and asking "is it exactly one" in three places is how they drift.
 */
export function soleSelected(selection, tables, zones) {
  if (selection.tables.size + selection.zones.size !== 1) return null;
  if (selection.tables.size === 1) {
    const [key] = selection.tables;
    const table = tables.find((t) => keyOf(t) === key);
    return table ? { kind: 'table', table } : null;
  }
  const [id] = selection.zones;
  const zone = zones.find((z) => z.id === id);
  return zone ? { kind: 'zone', zone } : null;
}
